#Plot size from center
plotSize: 20

#Plot block | After place of this block, plot will be created.
plotBlock: NOTE_BLOCK

#Limit of plots for player (default).
plotsPlayerLimit: 5

#Limit of plots for Vip player
#Permission: mineeasyplots.vip
plotsVipLimit: 10

