name: mineEasyPlots
version: ${project.version}
main: pl.mineEasyPlots.Main
api-version: 1.13
depend: [WorldGuard]
authors: [_arturek, Nikox3003]
description: Easy protection of your territory!
website: https://minecodes.pl/
commands:
  plot:
    description: Main plot command
    aliases: [p, plots]
  plotadmin:
    description: Manage plots
    aliases: [pa, plotsadmin]
permissions:
  mineeasyplots.limits.default:
    default: true